networks:
   default:
    driver: bridge
    name: roboshop
    external: true

services:
  mongodb:
   image: mongodb:v1
   container_name: mongodb


  catalogue:
   image: catalogue:v1
   container_name: catalogue
   depends_on:
     - mongodb

  redis:
   image: redis:7
   container_name: redis 

  user:
   image: user:v1
   container_name: user
   depends_on:
    - mongodb
    - redis

  cart:
   image: cart:v1
   container_name: cart
   depends_on:
     - redis
     - catalogue


  mysql:
    image: mysql:v1
    container_name: mysql
    

  shipping:
    image: shipping:v1
    container_name: shipping
    depends_on:
      - cart
      - mysql
  
  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    environment:
     - RABBITMQ_DEFAULT_USER:venkat
     - RABBITMQ_DEFAULT_PASS:Venkat@123
  payment:
    image: payment:v1
    container_name: payment
    environment:
     CART_HOST: cart
     CART_PORT: 8080
     USER_HOST: user
     USER_PORT: 8080
     AMQP_HOST: rabbitmq
     AMQP_USER: venkat
     AQMP_PASS: Venkat@123
    depends_on:
     - cart
     - user
     - rabbitmq
  frontend:
   image: frontend:v1
   container_name: frontend
   ports:
   - "8080:80"
   depends_on:
   - catalogue
   - cart
   - shipping
   - user
   - payment





