FROM node:20
WORKDIR /opt/server
COPY package.json .
COPY *.js .
RUN npm install
ENV  REDIS_URL="redis://redis:6379"\
     CATALOGUE_HOST="catalogue"\
     CATALOGUE_PORT="8080"


CMD ["node","server.js"]
